### ISSUE TITLE
Image load completion callback

### ISSUE THREAD

**Issue by edgarmkrtchyan** [Jaspero/ng-image-preload#1]
Hi,

Is there a way to fire a callback when the image is fully loaded?

Thanks.

**Comment by flauc** [comment]
I'm not entirely sure, but I think you can use this to check if the image on a particular item is fully loaded

https://www.w3schools.com/jsref/prop_img_complete.asp

**Comment by edgarmkrtchyan** [comment]
Thanks, @flauc. However I've done it this way:
```
this._preload.load(url).then(() => {
  // Image loaded
});
```
Hope this helps somebody.
