### ISSUE TITLE
Cannot find module '@jaspero/ng-image-preload'.  

### ISSUE THREAD

**Issue by akshgods** [Jaspero/ng-image-preload#2]
import { JasperoImagePreloadModule } from "@jaspero/ng-image-preload";

getting this error.

steps:
**install** 
npm install --save https://github.com/Jaspero/ng-image-preload

**import in appmodule** 
import { JasperoImagePreloadModule } from "@jaspero/ng-image-preload";

getting this error: Cannot find module '@jaspero/ng-image-preload'.

**Comment by flauc** [comment]
Should be working nicely now
